Wishlist Service
MiSArch/wishlist pull request #1
Opened 2024-01-04 16:16 UTC by legendofa

2024-01-05 07:26 UTC, nk-coding requested changes
I can't say too much about the code due to missing rust knowledge, maybe we have a team member with knowledge there. To me it looks good, except missing code documentation.

However I have a few notes about the GraphQL schema.
Note that I don't think all of this has to be done as part of this PR, but it would be good to create issues in Gropius for the stuff you decide to do in future PRs.
- most or all fields are missing documentation
- id inputs and outputs should use the `ID` scalar as type, not `String`
- mutations usually only take one input parameter named after the mutation (e.g. `AddWishlistInput` for `addWishlist`, which then contains all fields. IMHO this is a good style guide to follow here
- add/update mutations should return the created/updated object
- a many query should provide pagination features via the adapted connection standard we decide on. Here, in particular ordering and limiting are missing.
- As part of the GraphQL federation standard, one should not return the id of a related entity, but instead the entity itself (in this service the entities User and ProductVariant will then only consist of an id)
- `createdAt` / `lastUpdatedAt` should use the `DateTime` scalar
  definition from catalog: 
  ```graphql
  "A slightly refined version of RFC-3339 compliant DateTime Scalar"
  scalar DateTime
  ```
- `productVariantIds` should be also a connection with pagination support

2024-01-05 07:26 UTC, nk-coding commented on compose.yaml
> +  app:
this one currently does not work yet

2024-01-05 07:26 UTC, nk-coding commented on src/mutation_root.rs
> +fn uuid_parse(id: &String) -> Result<String, Error> {
missing documentation

2024-01-05 10:29 UTC, legendofa commented
Shall i also wrap mutations with only one argument, as delete, in a `DeleteWishlistInput` object?

2024-01-05 11:13 UTC, nk-coding commented
> Shall i also wrap mutations with only one argument, as delete, in a `DeleteWishlistInput` object?

Delete is a hard one. I do not really have a fixed opinion about this.  For create and update with one input, I would still say yes. Regarding delete, a benefit would be consistency, however I do also see why one would argue this is completely redundant.
One argument could be that in some cases, even delete could need more arguments, .e.g. a flag if some other entities should be deleted with the entity.
In any case, we should come to a decision we follow in all services.

2024-01-05 12:02 UTC, legendofa commented
Why should created/update return the object, isn't that overhead? Also did not find out yet how to implement pagination

2024-01-05 12:04 UTC, legendofa commented
> > Shall i also wrap mutations with only one argument, as delete, in a `DeleteWishlistInput` object?
> 
> Delete is a hard one. I do not really have a fixed opinion about this. For create and update with one input, I would still say yes. Regarding delete, a benefit would be consistency, however I do also see why one would argue this is completely redundant. One argument could be that in some cases, even delete could need more arguments, .e.g. a flag if some other entities should be deleted with the entity. In any case, we should come to a decision we follow in all services.

:+1:  I just left it concise for now, we can decide this in the next meeting then :)

2024-01-06 12:01 UTC, nk-coding commented
> Why should created/update return the object, isn't that overhead? Also did not find out yet how to implement pagination

First, for create, if you don't return it, how should the frontend know the id of the created object?
Second, often, when you create or update sth, you want to display the created/updated thing. Returning it allows you to do so without having to make another query.
Also, regarding efficiency, there should not be too much overhead. Returning it allows the user to fetch information from the created/update entity, however, GraphQL does not require you to do so (except at least one scalar field, but that is minimal overhead imho).

2024-01-06 17:52 UTC, legendofa commented
> First, for create, if you don't return it, how should the frontend know the id of the created object? Second, often, when you create or update sth, you want to display the created/updated thing. Returning it allows you to do so without having to make another query. Also, regarding efficiency, there should not be too much overhead. Returning it allows the user to fetch information from the created/update entity, however, GraphQL does not require you to do so (except at least one scalar field, but that is minimal overhead imho).

Sounds good, i have adapted it to return the UUID on creation and modification now :)

2024-01-06 18:05 UTC, nk-coding commented
> > First, for create, if you don't return it, how should the frontend know the id of the created object? Second, often, when you create or update sth, you want to display the created/updated thing. Returning it allows you to do so without having to make another query. Also, regarding efficiency, there should not be too much overhead. Returning it allows the user to fetch information from the created/update entity, however, GraphQL does not require you to do so (except at least one scalar field, but that is minimal overhead imho).
> 
> Sounds good, i have adapted it to return the UUID on creation and modification now :)

Again, it would be better to return the whole object to allow the user to decide what to get. In GraphQL, you basically never return just an id.
We should probably discuss if we want to support the Payload pattern (wrap the output in a Payload object).
See https://blog.logrocket.com/anti-patterns-graphql-schema-design/ (insufficient mutation response)

2024-01-08 13:15 UTC, nk-coding requested changes
- WishlistOrder should have fields `direction` and `field` to be consistent with other servics
- Missing documentation for WishlistOrder, WishlistOrderField, OrderDirection
- QueryRoot should be named Query (federation support)
- MutationRoot should be named Mutation (federation support)
- if possible, use ID scalar instead of custom UUID scalar (maybe just rename)
- wishlists query should return a WishlistConnection which also allows to get totalCount, hasNextPage
- field inputs are often not documented, instead the documentation is part of the field itself (however there is also documentation for ctx which does not exist in GraphQL)

2024-01-08 14:53 UTC, legendofa commented
Would it be possible to use UUIDs directly, as IDs lead to more error handling stuff? We only use UUIDs so no general IDs should be required

2024-01-08 14:54 UTC, legendofa commented
>     * field inputs are often not documented, instead the documentation is part of the field itself (however there is also documentation for ctx which does not exist in GraphQL)

Removed the `ctx`, do we really need duplicate docs there? The inputs are already the documented input object.

2024-01-08 15:41 UTC, nk-coding commented
> >     * field inputs are often not documented, instead the documentation is part of the field itself (however there is also documentation for ctx which does not exist in GraphQL)
> 
> Removed the `ctx`, do we really need duplicate docs there? The inputs are already the documented input object.
> 

Well if I could choose, I would add it only to the inputs themselves.

2024-01-09 19:05 UTC, legendofa commented
I have added Connection support in this PR. Changed the field docs to the annotation style, but i am not sure if it turns out the way we want it to be. Next up will be the federation support, but will create a new PR for that.

2024-01-09 22:49 UTC, nk-coding requested changes
- In GraphQL, maybe rename BaseConnection to WishlistConnection as it is a connection for Wishlists (also we will have clashes otherwise in the future).
- BaseConnection and Wishlist are both missing GraphQL descriptions for all fields

2024-01-09 22:52 UTC, legendofa commented
> * In GraphQL, maybe rename BaseConnection to WishlistConnection as it is a connection for Wishlists (also we will have clashes otherwise in the future).
> 
>     * BaseConnection and Wishlist are both missing GraphQL descriptions for all fields

I am aware of this and did not find out how to rename it, there is no such thing as inheritance in Rust. I could make it non-generic instead.

2024-01-09 23:21 UTC, nk-coding approved these changes

2024-01-09 23:21 UTC, merged